// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

// export default function Layout({ children }) {
//   return (
//     <div className="bg-gray-100 min-h-screen">
//       {/* Navigation Bar */}
//       <nav className="bg-blue-600 text-white p-4">
//         <ul className="flex justify-center space-x-6 text-lg font-semibold">
//           <li>
//             <a href="/" className="hover:text-yellow-300 transition">Home</a>
//           </li>
//           <li>
//             <a href="/WeatherSection" className="hover:text-yellow-300 transition">Weather</a>
//           </li>
//           <li>
//             <a href="/CryptoSection" className="hover:text-yellow-300 transition">Crypto</a>
//           </li>
//           <li>
//             <a href="/NewsSection" className="hover:text-yellow-300 transition">News</a>
//           </li>
//         </ul>
//       </nav>

//       {/* Main Content */}
//       <main className="container mx-auto p-6">{children}</main>
//     </div>
//   );
// }


// import './globals.css'; // Ensure Tailwind is imported

// export default function Layout({ children }) {
//   return (
//     <div className="bg-gray-100 min-h-screen">
//       {/* Navigation Bar */}
//       <nav className="bg-blue-600 text-white p-4">
//         <ul className="flex justify-center space-x-6 text-lg font-semibold">
//           <li><a href="/" className="hover:text-yellow-300 transition">Home</a></li>
//           <li><a href="/WeatherSection" className="hover:text-yellow-300 transition">Weather</a></li>
//           <li><a href="/CryptoSection" className="hover:text-yellow-300 transition">Crypto</a></li>
//           <li><a href="/NewsSection" className="hover:text-yellow-300 transition">News</a></li>
//         </ul>
//       </nav>

//       {/* Main Content */}
//       <main className="container mx-auto p-6">{children}</main>
//     </div>
//   );
// }


// src/app/layout.js
"use client";

import { Provider } from "react-redux";
import { store } from "@/redux/store";
import "./globals.css"; // Ensure Tailwind CSS is imported

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
